version: "3"

services:
  ngx-snake-db:
    image: mariadb
    restart: always
    container_name: ngx-snake-db
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: ngx_snake
    ports:
      - '3306:3306'
    volumes:
      - ./mountpoints/db/:/var/lib/mysql

  ngx-snake-db-test:
    image: mariadb
    restart: always
    container_name: ngx-snake-db-test
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: ngx_snake
    ports:
      - '3307:3306'
    volumes:
      - ./mountpoints/db-test/:/var/lib/mysql
