name: node build lint test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:

  checkout:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout projekt
        uses: actions/checkout@v2

  backend:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/setup-node@v2
      - name: CI build
        run: npm ci
      - name: Run test
        run: npm test
      # - run: npm run lint # disabled because of lint errors

  frontend:
    runs-on: ubuntu-18.04
    steps:
      - name: CI build
        working-directory: frontend
        run: npm ci
      - name: Run test
        working-directory: frontend
        run: npm test
      # - run: npm run lint # disabled because of lint errors
